/* Creación de usuarios si está trabajando con BD Oracle XE */
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER COOPERA IDENTIFIED BY "Duocadmin25"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER COOPERA QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO COOPERA;
GRANT "RESOURCE" TO COOPERA;
ALTER USER COOPERA DEFAULT ROLE "RESOURCE";
grant all privileges to Coopera;