alter SESSION set "_oracle_script"=true;

CREATE USER OE_BDY1103 IDENTIFIED BY OE2S2025;

ALTER USER OE_BDY1103 DEFAULT TABLESPACE USERS
              QUOTA UNLIMITED ON USERS;

ALTER USER OE_BDY1103 TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO OE_BDY1103;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO OE_BDY1103;